# config.py
import os

# Directory where you keep your .gguf models
MODELS_DIRECTORY = r"E:\LL STUDIO"

# Default inference settings — expanded with more useful parameters
DEFAULT_N_CTX = 4096
DEFAULT_N_GPU_LAYERS = 99   
DEFAULT_MAX_TOKENS = 1024
DEFAULT_TEMPERATURE = 0.7
DEFAULT_TOP_P = 0.95
DEFAULT_TOP_K = 40
DEFAULT_REPEAT_PENALTY = 1.1
DEFAULT_PRESENCE_PENALTY = 0.0
DEFAULT_FREQUENCY_PENALTY = 0.0
DEFAULT_MIROSTAT = 0  
DEFAULT_MIROSTAT_TAU = 5.0
DEFAULT_MIROSTAT_ETA = 0.1
DEFAULT_TYPICAL_P = 1.0
DEFAULT_TFS_Z = 1.0  