name: Bug Report
description: Report something that isn't working correctly
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please fill in as much detail as you can.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this behavior?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of AgentNate is affected?
      options:
        - Chat / Agent System
        - n8n Workflows
        - ComfyUI / Image Generation
        - Text-to-Speech
        - Music Generation
        - Model Loading / Providers
        - GPU / System Monitoring
        - Installation / Setup
        - UI / Frontend
        - API / Backend
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your system info (GPU, RAM, Windows version, etc.)
      placeholder: |
        - OS: Windows 10/11
        - GPU: NVIDIA RTX 3090 (24GB)
        - RAM: 32GB
        - Python: (from install.bat)
      render: markdown

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Paste any error messages from the Logs tab or console.
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem.
