name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for AgentNate? We'd love to hear it.

  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: A clear description of what you'd like to see.
      placeholder: What should it do?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why is this useful?
      description: Explain the use case or problem this would solve.
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which area of AgentNate would this affect?
      options:
        - Chat / Agent System
        - n8n Workflows
        - ComfyUI / Creative Tools
        - Text-to-Speech
        - Music Generation
        - Model Management
        - New Provider Support
        - UI / Frontend
        - API / Backend
        - Installation / Portability
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you thought of other ways to accomplish this?

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Screenshots, mockups, links to related projects, etc.
